development:
  adapter: postgresql
  encoding: unicode
  database: cazalets_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: cazalets_test
  host: localhost
  pool: 5