development:
  adapter: postgresql
  encoding: unicode
  database: homefront_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: homefront_test
  host: localhost
  pool: 5