development:
  adapter: postgresql
  encoding: unicode
  database: macbeth_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: macbeth_test
  host: localhost
  pool: 5