development:
  adapter: postgresql
  encoding: unicode
  database: archers_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: archers_test
  host: localhost
  pool: 5